# Generated by Django 4.0.6 on 2022-08-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_traintest_from_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['name'], 'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
    ]
