# Generated by Django 4.0.6 on 2022-08-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_alter_train_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['travel_time'], 'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
    ]
